import React, { useState, useEffect } from 'react';
import { Sparkles, RefreshCw, ShieldCheck } from 'lucide-react';
import type { AIInsightItem } from '../types';
import { api } from '../services/api';

export const InsightsView: React.FC = () => {
  const [insights, setInsights] = useState<AIInsightItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [activeCategory, setActiveCategory] = useState<string>('All');

  const fetchInsights = async () => {
    setLoading(true);
    try {
      const res = await api.getInsights();
      setInsights(res.insights || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchInsights();
  }, []);

  const handleRefresh = async () => {
    setRefreshing(true);
    try {
      const res = await api.generateInsights();
      setInsights(res.insights || []);
    } catch (err) {
      console.error(err);
    } finally {
      setRefreshing(false);
    }
  };

  const categories = ['All', 'Sleep', 'Energy', 'Stress', 'Vitals', 'Lifestyle'];

  const filteredInsights = activeCategory === 'All'
    ? insights
    : insights.filter(i => i.category.toLowerCase() === activeCategory.toLowerCase());

  return (
    <div className="space-y-6 animate-fade-in pb-16">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-slate-900 dark:text-white tracking-tight flex items-center space-x-2">
            <Sparkles className="w-6 h-6 text-vital-500" />
            <span>Claude AI Insights</span>
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
            Personalized, non-diagnostic observations generated by analyzing your structured health statistics.
          </p>
        </div>

        <button
          onClick={handleRefresh}
          disabled={refreshing}
          className="px-4 py-2.5 rounded-xl bg-vital-600 hover:bg-vital-500 text-white font-bold text-xs shadow-soft flex items-center justify-center space-x-2 disabled:opacity-50 self-start sm:self-auto"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${refreshing ? 'animate-spin' : ''}`} />
          <span>{refreshing ? 'Analyzing Data...' : 'Refresh AI Analysis'}</span>
        </button>
      </div>

      {/* Non-diagnostic Banner */}
      <div className="p-4 rounded-2xl bg-vital-50/70 dark:bg-vital-950/40 border border-vital-200 dark:border-vital-800 flex items-start space-x-3 text-xs text-vital-900 dark:text-vital-200">
        <ShieldCheck className="w-5 h-5 text-vital-500 flex-shrink-0 mt-0.5" />
        <div>
          <span className="font-bold block mb-0.5">Empirical Pattern Observations</span>
          <span>
            VITAL AI observations are derived purely from co-occurrences and baseline shifts in your logged data. They are for self-understanding and are not medical diagnoses.
          </span>
        </div>
      </div>

      {/* Category Tabs */}
      <div className="flex items-center space-x-2 overflow-x-auto py-1 no-scrollbar">
        {categories.map((cat) => (
          <button
            key={cat}
            onClick={() => setActiveCategory(cat)}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
              activeCategory === cat
                ? 'bg-vital-600 text-white shadow-sm'
                : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Insights Grid */}
      {loading ? (
        <div className="p-8 text-center text-xs text-slate-400">Analyzing personal baselines...</div>
      ) : filteredInsights.length === 0 ? (
        <div className="glass-card p-8 rounded-3xl text-center text-xs text-slate-400">
          No observations available for this category yet. Log more daily entries to unlock deeper pattern detection.
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filteredInsights.map((item) => (
            <div
              key={item.id || item.title}
              className="glass-card p-6 rounded-3xl border border-slate-200/80 dark:border-slate-800/80 space-y-3 flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="px-2.5 py-0.5 rounded-full bg-vital-100 dark:bg-vital-950 text-vital-700 dark:text-vital-300 text-[10px] font-extrabold uppercase">
                    {item.category}
                  </span>
                  <span className="text-[10px] font-semibold text-slate-400 bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded-md">
                    {item.observation_type}
                  </span>
                </div>

                <h3 className="font-extrabold text-base text-slate-900 dark:text-white mb-2">
                  {item.title}
                </h3>

                <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                  {item.content}
                </p>
              </div>

              <div className="pt-3 border-t border-slate-200/50 dark:border-slate-800/50 flex items-center justify-between text-[10px] text-slate-400">
                <span>Observational pattern</span>
                <span className="uppercase font-bold text-vital-600 dark:text-vital-400">VITAL AI Verified</span>
              </div>
            </div>
          ))}
        </div>
      )}

    </div>
  );
};
